version: '3'
services:
  organice:
    image: 'twohundredok/organice:latest'
    ports:
      - '5000:5000'
    logging:
      driver: json-file
    environment:
      ORGANICE_WEBDAV_URL: 'https://onedrive.ayanamimcy.top/org/'
